#version 430 core

layout (local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;

layout (std430, binding = 0) buffer Buffer {
	uint buf[];
};
layout (location = 0) uniform uvec4 val[3];
layout (location = 3) uniform uint size;
layout (location = 4) uniform uint offset;
layout (location = 5) uniform uint length;

void main() {
	uint ind = offset +
		( gl_NumWorkGroups.x * gl_NumWorkGroups.y * gl_WorkGroupID.z
		+ gl_NumWorkGroups.x * gl_WorkGroupID.y
		+ gl_WorkGroupID.x ) * 1024 + gl_LocalInvocationID.x;
	if (ind < length) {
		uint i = ind%size;
		buf[ind] = val[i/4][i%4];
	}
}

